"""add calificaciones table

Revision ID: 6a2607415a70
Revises: 0a0b4c2f3292
Create Date: 2025-11-11 12:51:03.878645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a2607415a70'
down_revision = '0a0b4c2f3292'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###